### ISSUE TITLE
fortran 8.2 for MAC Mojave

### ISSUE THREAD

**Issue by lesl1** [fxcoudert/gfortran-for-macOS#1]
Package from this website seems to install properly, but I cannot figure out how to specify libraries.  No matter where I put them( local, /usr/local/lib) they cannot be found by the loader (ld) after compilation.  The gfortran 6.3 package would, at least, load them when I placed them in /usr/local/lib.  Any suggestions?  I have had to revert to gfortran 6.3 to continue my efforts.  Thanks for any suggestions.  I just recently upgraded to MAC OS mojave and Xcode 10.1 with devel tools.

**Comment by fxcoudert** [comment]
The `-L` flag can be used to indicate to the compiler where libraries are found. If you have libraries in `$HOME/local/lib`, for example, you would compile with `-L $HOME/local/lib`.

**Comment by lesl1** [comment]
fxcoudert,

	I have tried using the -L option, but to no avail.  Do you have an example “make” file that demonstrates a fortran compile with gfortran 8.2 on a Mac running Mojave that attaches user developed libraries?  These features seemed to be partially broken in past distributions;  but, at least, the default location “/usr/local/lib” was always searched so I could put my libraries there(a nuisance, but it worked).  Now, that doesn’t even work.  This is very frustrating.  I have reinstalled gfortran 6.2 and am back to work.  I would like to take advantage of the latest compiler, but I don’t seem to be able to.  I could include my make files, if that would help.

	Thanks for any help you can provide in this matter,

	lesl1

**Comment by fxcoudert** [comment]
I'm sorry, I won't have time to debug your makefiles. I can confirm that using the `-L` option makes `gfortran` find libraries on my system. If you have a simple reproducible example (not a makefile, but one compilation command) that makes `gfortran` misbehave, you're welcome to post it here.
