### ISSUE TITLE
Gfortran8 and Gfortran10 Can't create standalone executables using -static-libgfortran

### ISSUE THREAD

**Issue by jelanier** [fxcoudert/gfortran-for-macOS#10]
Here is an example command line:
gfortran -Og -ffast-math -fno-automatic -static-libgfortran nec2dxs_JL.f -o nec2dxsJL

It works on machine with the compiler, but executable on a machine without Gfortran shows
 exit; dyld: Library not loaded: /usr/local/gfortran/lib/libquadmath.0.dylib

libquadmath.0.dylib and libquadmath.dylib are in the gfortran lib directory.

Any ideas?

Jim

**Comment by fxcoudert** [comment]
The compiler needs a `-static-libquadmath` flag, but that does not exist. It is a known GCC limitation, sadly: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=46539
