### ISSUE TITLE
Issue in uninstalling gfortran

### ISSUE THREAD

**Issue by senna1128** [fxcoudert/gfortran-for-macOS#11]
Hi,

I installed gfortran 10.2 for Catalina (macOS 10.15), but I found my Matlab2017a does not support this version. I tried to uninstall it and install gfortran 4.9 version. I ran the command
sudo rm -r /usr/local/gfortran /usr/local/bin/gfortran

But after I downloaded the gfortran 4.9 from [https://github.com/fxcoudert/gfortran-for-macOS/releases/tag/4.9.0](https://github.com/fxcoudert/gfortran-for-macOS/releases/tag/4.9.0), and opened .pkg file to install, it said that my disk has a newer version of gfortran so that I cannot install. So the command 
sudo rm -r /usr/local/gfortran /usr/local/bin/gfortran
cannot fully uninstall the gfortran. 

How to fix this issue?

Best
Sen

**Comment by fxcoudert** [comment]
You're right, I didn't realise macOS was keeping a record. After removing the files, you can let the OS know you've removed them with `pkgutil --forget com.gnu.gfortran`. So the full uninstall instructions should be:

```
sudo rm -r /usr/local/gfortran /usr/local/bin/gfortran
sudo pkgutil --forget com.gnu.gfortran
```
