### ISSUE TITLE
zsh: bad CPU type in executable: gfortran

### ISSUE THREAD

**Issue by LIU2019YH** [fxcoudert/gfortran-for-macOS#14]
Hi.
Thanks for your work.
I'm trying to install gfortran in MacOS BigSur 11.1.
I downloaded gfortran from "https://github.com/fxcoudert/gfortran-for-macOS/releases", and installed the version as "gfortran 11-experimental-2 for ARM Big Sur (macOS 11)". 
However, I got "zsh: bad CPU type in executable: gfortran" when I typed "gfortran" in the terminal.
Could you help me to check? How to solve this problem?

Thank you very much.

**Comment by fxcoudert** [comment]
The macOS 11 pre-releases are for Apple Silicon (ARM) only.
For Intel, the latest available version is the 10.12 release: https://github.com/fxcoudert/gfortran-for-macOS/releases/tag/10.2

**Comment by LIU2019YH** [comment]
> The macOS 11 pre-releases are for Apple Silicon (ARM) only.
> For Intel, the latest available version is the 10.12 release: https://github.com/fxcoudert/gfortran-for-macOS/releases/tag/10.2

Thank you very much.
The issue has been solved after installed 10.12.
