### ISSUE TITLE
cross-compiling for arm64 target on x86_64 host?

### ISSUE THREAD

**Issue by ogrisel** [fxcoudert/gfortran-for-macOS#15]
Is it possible to use the [10.2-bigsur-intel](https://github.com/fxcoudert/gfortran-for-macOS/releases/tag/10.2-bigsur-intel) release to cross-compile to target arm64 target on a x86_64 host?

**Comment by fxcoudert** [comment]
No. To my knowledge no-one is hosting a x86_64-to-arm64 cross-compiler. It's possible to build one from sources at https://github.com/iains/gcc-darwin-arm64 or https://github.com/fxcoudert/gcc/tree/gcc-10-arm but it's not trivial. I've documented some steps to do that at https://github.com/iains/gcc-darwin-arm64/issues/34

**Comment by ogrisel** [comment]
Thank you for the quick feedback!
