### ISSUE TITLE
gfortran-ARM-11.0-BigSur.pkg can't be opened because Apple cannot check it for malicious software

### ISSUE THREAD

**Issue by ogrisel** [fxcoudert/gfortran-for-macOS#16]
When trying to install the `.pkg` file of the latest experimental release on Big Sur / Apple M1, I get:

<img width="264" alt="Screenshot 2021-01-11 at 18 15 53" src="https://user-images.githubusercontent.com/89061/104215490-1c52f580-5439-11eb-8acf-c58e552c519c.png">

I have a similar problem if I try to execute the `gfortran` binary from `gfortran-ARM-11.0-BigSur.tar.xz`.

**Comment by ogrisel** [comment]
Opening the folder in Finder, then right clicking or option clicking on the `.pkg` file and then clicking on the "Open" link works (with a warning).

**Comment by fxcoudert** [comment]
Yes, I've been thinking about having a notarised package (allowing it to open seamlessly) but it's quite an effort… I guess I'll do it at some point

**Comment by russell2440** [comment]
> Opening the folder in Finder, then right clicking or option clicking on the `.pkg` file and then clicking on the "Open" link works (with a warning).
Hi,
Not sure how to 'right click' with macbook air.
I tried opening with finder 'open', and it still won't allow it.
Had anyone a solution to this? I think i've looked at all links on this here, but aside from notorizing idea below, i don't see a solution...
Ty Russ

**Comment by gaborcsardi** [comment]
> Not sure how to 'right click' with macbook air.

Two finger tap, or CTRL + tap/click usually, depending on configuration.
