### ISSUE TITLE
Bad CPU type in executable gfortran

### ISSUE THREAD

**Issue by loukesio** [fxcoudert/gfortran-for-macOS#17]
Thank you for the new release of gfortran
I have MAC big Sur and its all updated to the latest version as for today 15.01.2021.

I have downloaded and installed gfortran-ARM-11.0-BigSur.pkg
but when I try to update a package in R or search via terminal I get this message 
bash: /usr/local/bin/gfortran: Bad CPU type in executable

any idea why?

Thank you for your time

**Comment by fxcoudert** [comment]
The macOS 11 pre-releases are for Apple Silicon (ARM) only.
For Intel, the latest available version is the 10.12 release: https://github.com/fxcoudert/gfortran-for-macOS/releases/tag/10.2

**Comment by yasinasar** [comment]
Thanks very much, I could not install some packages in R. But after installing gfortran 10.2 for maxOS Big Sur 11.4, I am able to install those packages.
