### ISSUE TITLE
Issue with gfortran 8.2 on Mojave

### ISSUE THREAD

**Issue by raultoral** [fxcoudert/gfortran-for-macOS#18]
I recently updated from gfortran v5.1 to v8.2.0 using  installer available at https://github.com/fxcoudert/gfortran-for-macOS/releases/tag/8.2. I try to run the simple program named test1.f90 in an IMAC with Intel Core i5

---

program test1
  write(6,*) '1'
  open(8,file='gamma.out')
  write(6,*) '2'
end program test1

----

I compile it using 
gfortran test1.f90 -o test1.x 
and when running it I get the output

----

 1
At line 3 of file test1.f90 (unit = 8, file = '')
Fortran runtime error: Bad address

----

Then I tried the program test2.f90:

----

program test2
  write(6,*) '1'
  x=1.0
  write(6,*) '2'
  write(6,*) x
  write(6,*) '3'
  write(6,'(f10.5)') x
  write(6,*) '4'
end program test2

---

The output I get now is:

---

 1
 2
   1.00000000    
 3
Program received signal SIGSEGV: Segmentation fault - invalid memory reference.
Backtrace for this error:
#0  0x104c622d2
#1  0x104c62a8e
#2  0x7fff6f4c1b5c
#3  0x104d222a0
#4  0x104d31197
#5  0x104c5bdf4
#6  0x104c5bebc
Segmentation fault

---

Any ideas of what can be wrong?

**Comment by fxcoudert** [comment]
Can you run the compiled executable under `lldb` to get a backtrace?

**Comment by raultoral** [comment]
I am not very much familiar with lddb. I did:

 >lldb test1.x -c
(lldb) target create "test1.x"
Current executable set to 'test1.x' (x86_64).
(lldb) run
Process 6691 launched: '/Users/raul/ownCloud/random/test1.x' (x86_64)
  1
At line 3 of file test1.f90 (unit = 8, file = '')
Fortran runtime error: Bad address
Process 6691 exited with status = 2 (0x00000002)
(lldb) exit

 >

Is this what you wanted to see?

Thanks

Raul

**Comment by fxcoudert** [comment]
I don't have access to a Mojave computer anymore, so I will not be able to debug this. If 6.3 works for you, I suggest using that :) Another option to have access to more recent compilers is Homebrew: https://brew.sh

**Comment by raultoral** [comment]
Thanks. Brew gives me a lot of trouble. gfortran Using 6.3 is probably 
good enough for me. In fact, I was using 5.1 and never had any 
complaints....

**Comment by fxcoudert** [comment]
I am going to close this because I cannot fix it: I don't have access to Mojave anymore.
