### ISSUE TITLE
Unable to use gfortran

### ISSUE THREAD

**Issue by wenlanzhang** [fxcoudert/gfortran-for-macOS#19]
I am working on a MAC Big Sur 11.1.
I have downloaded the .phg file(https://github.com/fxcoudert/gfortran-for-macOS/releases) and managed to install. 
However, when I try to run gfortran in Terminal, I got:
`zsh: bad CPU type in executable: gfortran`

Also, when I run other file that needs gfortran, it doesn't work, and show me this error:
`(base) zhangwenlan@zhangwenlan-MBP clawpack % pip install -e .
Obtaining file:///Users/zhangwenlan/clawpack
Requirement already satisfied: numpy>=1.14 in /Users/zhangwenlan/.local/lib/python3.8/site-packages (from clawpack==0.0.0) (1.19.5)
Requirement already satisfied: matplotlib>=1.0.1 in /Users/zhangwenlan/.local/lib/python3.8/site-packages (from clawpack==0.0.0) (3.3.3)
Requirement already satisfied: kiwisolver>=1.0.1 in /Users/zhangwenlan/.local/lib/python3.8/site-packages (from matplotlib>=1.0.1->clawpack==0.0.0) (1.3.1)
Requirement already satisfied: pillow>=6.2.0 in /Users/zhangwenlan/.local/lib/python3.8/site-packages (from matplotlib>=1.0.1->clawpack==0.0.0) (8.1.0)
Requirement already satisfied: cycler>=0.10 in /Users/zhangwenlan/.local/lib/python3.8/site-packages (from matplotlib>=1.0.1->clawpack==0.0.0) (0.10.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3 in /Users/zhangwenlan/miniconda3/lib/python3.8/site-packages (from matplotlib>=1.0.1->clawpack==0.0.0) (2.4.7)
Requirement already satisfied: python-dateutil>=2.1 in /Users/zhangwenlan/miniconda3/lib/python3.8/site-packages (from matplotlib>=1.0.1->clawpack==0.0.0) (2.8.1)
Requirement already satisfied: six in /Users/zhangwenlan/miniconda3/lib/python3.8/site-packages (from cycler>=0.10->matplotlib>=1.0.1->clawpack==0.0.0) (1.15.0)
Installing collected packages: clawpack
  Running setup.py develop for clawpack
    ERROR: Command errored out with exit status 1:
     command: /Users/zhangwenlan/miniconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/Users/zhangwenlan/clawpack/setup.py'"'"'; __file__='"'"'/Users/zhangwenlan/clawpack/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: /Users/zhangwenlan/clawpack/
    Complete output (1 lines):
    error: extension 'clawpack.riemann.acoustics_1D_ptwise' has Fortran sources but no Fortran compiler found
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/zhangwenlan/miniconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/Users/zhangwenlan/clawpack/setup.py'"'"'; __file__='"'"'/Users/zhangwenlan/clawpack/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
(base) zhangwenlan@zhangwenlan-MBP clawpack % `

I want to know whether there is any solution for this, many thanks.

**Comment by fxcoudert** [comment]
The macOS 11 pre-releases are for Apple Silicon (ARM) only.
For Intel, the latest available version is the 10.12 release: https://github.com/fxcoudert/gfortran-for-macOS/releases/tag/10.2

See also: https://github.com/fxcoudert/gfortran-for-macOS/issues/14
