### ISSUE TITLE
gfortran-10.2-BigSur

### ISSUE THREAD

**Issue by hkiwan11** [fxcoudert/gfortran-for-macOS#21]
I'm trying to install gfortran mentioned in the title but I keep getting this message "“gfortran.pkg” can’t be opened because Apple cannot check it for malicious software." how do I fix this issue?

**Comment by fxcoudert** [comment]
See https://support.apple.com/HT202491 for opening non-certified packages

**Comment by hkiwan11** [comment]
that didn't rally help. I have my setting set to open from app store or identified developers

**Comment by hkiwan11** [comment]
![Screen Shot 2021-03-08 at 2 47 34 PM](https://user-images.githubusercontent.com/79884405/110373254-4c73da80-801d-11eb-9e9c-fd0a1a493636.png)

**Comment by fxcoudert** [comment]
Look at “How to open an app that hasn’t been notarized or is from an unidentified developer”

**Comment by fxcoudert** [comment]
I have now created a new installer (for GCC 11.2) with signed binaries and notarized package. It should not have this warning anymore about “cannot be checked for malicious software”.

Please test it and report if you experience issues: https://github.com/fxcoudert/gfortran-for-macOS/releases/tag/11.2-bigsur-intel
