### ISSUE TITLE
issue when opening gfortran-10.2-BigSur-Intel.dmg

### ISSUE THREAD

**Issue by sjoertvv** [fxcoudert/gfortran-for-macOS#22]
<img width="248" alt="Screen Shot 2021-03-03 at 16 07 36" src="https://user-images.githubusercontent.com/1986576/109826256-e6610f00-7c3a-11eb-81db-87ed343508e3.png">

**Comment by fxcoudert** [comment]
You can open it following the documentation here: https://support.apple.com/HT202491

**Comment by sjoertvv** [comment]
Thanks for the reply. I'm familiar with the steps in the Apple support document you shared. This worked for me in the past. The problem is that the final step, "Open Anyway", seems to be no longer possible in Big Sur.

**Comment by fxcoudert** [comment]
I have now created a new installer (for GCC 11.2) with signed binaries and notarized package. It should not have this warning anymore about “cannot be checked for malicious software”.

Please test it and report if you experience issues: https://github.com/fxcoudert/gfortran-for-macOS/releases/tag/11.2-bigsur-intel
