### ISSUE TITLE
gfortran: error: unrecognized command-line option

### ISSUE THREAD

**Issue by wenhaoxuan** [fxcoudert/gfortran-for-macOS#25]
Hi,

I'm trying to install a package that requires gfortran. I installed the gfortran for Big Sur successfully, but get these errors when trying to compile the package:
```
gfortran: warning: this compiler does not support X86 (arch flags ignored)
gfortran: error: unrecognized command-line option ‘-msse’
gfortran: error: unrecognized command-line option ‘-msse2’
gfortran: error: unrecognized command-line option ‘-m3dnow’
```
I'm not sure how to fix this after some googling.

**Comment by fxcoudert** [comment]
If you're using an ARM computer, you shouldn't pass those flags, because they are specific to the Intel architecture. Report this as a bug to the package you're trying to build.
