### ISSUE TITLE
'“gfortran.pkg” can’t be opened because Apple cannot check it for malicious software.'

### ISSUE THREAD

**Issue by etzkorn** [fxcoudert/gfortran-for-macOS#27]
Any ideas? (image below). Running Catalina 10.15.7.

<img width="414" alt="Screen Shot 2021-05-16 at 10 28 53 PM" src="https://user-images.githubusercontent.com/14077662/118425069-64f41700-b696-11eb-8189-7d7de9b6dde4.png">

**Comment by praveenkumarpgiindia** [comment]
Facing the same issue. Not able to install gfortran both via package as well as folder. As the console is saying that Apple cannot check it for malicious software. I am running macOs Big Sur.

**Comment by fxcoudert** [comment]
See solutions posted here: https://github.com/fxcoudert/gfortran-for-macOS/issues/16
and there: https://github.com/fxcoudert/gfortran-for-macOS/issues/21

**Comment by fxcoudert** [comment]
I have now created a new installer (for GCC 11.2) with signed binaries and notarized package. It should not have this warning anymore about “cannot be checked for malicious software”.

Please test it and report if you experience issues: https://github.com/fxcoudert/gfortran-for-macOS/releases/tag/11.2-bigsur-intel
