### ISSUE TITLE
Apple not allowing install

### ISSUE THREAD

**Issue by RAZingarelli** [fxcoudert/gfortran-for-macOS#28]
Clicking on gfortran.pkg produces a pop-up with "“gfortran.pkg” can’t be opened because Apple cannot check it for malicious software."

Any hints much appreciated.

**Comment by fxcoudert** [comment]
See solutions posted here: https://github.com/fxcoudert/gfortran-for-macOS/issues/16
and there: https://github.com/fxcoudert/gfortran-for-macOS/issues/21

**Comment by RAZingarelli** [comment]
Thank you.  Digging in now.

**Comment by fxcoudert** [comment]
I have now created a new installer (for GCC 11.2) with signed binaries and notarized package. It should not have this warning anymore about “cannot be checked for malicious software”.

Please test it and report if you experience issues: https://github.com/fxcoudert/gfortran-for-macOS/releases/tag/11.2-bigsur-intel
