### ISSUE TITLE
GCC 11.x build is failing on MBP (Intel) with macOS Big Sur

### ISSUE THREAD

**Issue by rakeshphys** [fxcoudert/gfortran-for-macOS#34]
Thanks a lot for providing gfortran binary for MacOS community.

Moreover, I am also trying to build GCC 11.x on my MBP (intel) with MacOS 11.5.2 (Big Sur) but ended unsuccessfully with compare, bubble errors (please see the attached screenshot). I followed the following build instructions:

tar -xzf gcc-11.2.0.tar.xz
cd gcc-11.2.0
./contrib/download_prerequisites 
./configure --prefix=/opt/gnu/gcc-11.2.0 --enable-static --enable-shared --enable-languages=all --disable-multilib --with-sysroot=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk

I tried with --disable-multilib and without it. In each case, the gcc build fails. Could you please help me out?

P.S.: On the same machine, I successfully build GCC 10.x a long time ago with the above instructions.

[
<img width="578" alt="Screen Shot 2021-09-09 at 4 39 01 PM" src="https://user-images.githubusercontent.com/15262356/132802197-b72135cc-e041-413b-adbd-b9408ff09e42.png">
](url)

**Comment by virk** [comment]
I have got a similar problem. Does anybody here perhaps know where I can find a forum for to ask some fortran specific questions? F.e. can I compile an executable for an INTEL Big Sur MBP with the M1-Fortran?

**Comment by fxcoudert** [comment]
The error in comparison of object files at stage 3 is a bug introduced by Apple in Xcode 12.5 and later on Intel. See https://gcc.gnu.org/bugzilla/show_bug.cgi?id=100340 for details

You can work around it by passing `--without-build-config` to `configure`.
