### ISSUE TITLE
create a developer-signed or notarised update (to 11.2)

### ISSUE THREAD

**Issue by dimpase** [fxcoudert/gfortran-for-macOS#35]
The latest release is not signed/notarised, and moreover there is now gcc 11.2 available (in Homebrew as well).

**Comment by fxcoudert** [comment]
I don't intend to track all releases. For that, I recommend [Homebrew](https://brew.sh) indeed.

Regarding notarisation, I am aware but it is very complex.

**Comment by dimpase** [comment]
How is Homebrew dealing with notarisation? I tried to find out, but it seems hidden somewhere.

**Comment by fxcoudert** [comment]
Homebrew does not notarise, because it's a command-line tool so it doesn't need to (unlike my installer package). On ARM, it re-signs all executables and libraries upon installation (using _ad hoc_ code signing).

**Comment by dimpase** [comment]
Right, then why there is no .tar.xz archive provided for the latest release?

**Comment by fxcoudert** [comment]
I have now created a new installer (for GCC 11.2) with signed binaries and notarized package. It should not have this warning anymore about “cannot be checked for malicious software”.

Please test it and report if you experience issues: https://github.com/fxcoudert/gfortran-for-macOS/releases/tag/11.2-bigsur-intel

**Comment by dimpase** [comment]
installs and works fine on the latest macOS 11 - used it to build and test
scipy.
