### ISSUE TITLE
Problem opening gfortran.pkg

### ISSUE THREAD

**Issue by jeff0708** [fxcoudert/gfortran-for-macOS#36]
I have Mac OS 11.6.
When I try to open gfortran.pkg (from gfortran-intel-11.1-BigSur.dmg), I get the following error message on my Mac:

"gfortran.pkg" can't be opened because Apple cannot check it for malicious software.  This software needs to be updated.  Contact the developer for more information.

Any solution for this problem?

**Comment by fxcoudert** [comment]
This should work: https://github.com/fxcoudert/gfortran-for-macOS/issues/27

**Comment by jeff0708** [comment]
Thank you.

I was able to install gfortran according to these directions, but now I
can't locate it on my computer.
If I search for gfortran in Find, it does not appear.
If I type gfortran in Terminal, I get the following error:   *gfortran:* *fatal
error: *no input files
compilation terminated.

Jeff

**Comment by fxcoudert** [comment]
```
$ gfortran
gfortran: fatal error: no input files
compilation terminated.
```

This is the normal output if you don't list any file to compile.

**Comment by jeff0708** [comment]
You can tell I'm a novice.
Everything is fine now.
Jeff

**Comment by fxcoudert** [comment]
I have now created a new installer (for GCC 11.2) with signed binaries and notarized package. It should not have this warning anymore about “cannot be checked for malicious software”.

Please test it and report if you experience issues: https://github.com/fxcoudert/gfortran-for-macOS/releases/tag/11.2-bigsur-intel

**Comment by jeff0708** [comment]
I tested it.
No more warning.
Jeff
