### ISSUE TITLE
Cannot install macOS R toolchain installer

### ISSUE THREAD

**Issue by mjsspilka** [fxcoudert/gfortran-for-macOS#37]
#### Summary:
Downloaded macOS R toolchain installer but installation fails on my Mac machine running Big Sur 11.6. R version is 4.0.2.

#### Description:
I'm trying to download Rstan to resolve an issue with installing the brms R pacakge. However, the macOS R toolchain installer fails. I can see that i has made a backup up my Makevars file. However, I don't have an Renviron file.

Any help resolving this would be much appreciated. Thank you.

**Comment by fxcoudert** [comment]
- I do not maintain the R toolchain, nor its installer.
- I have not even used R in many years.
- You provide no links to the files that were downloaded and installed.
- You provide no error message, screenshot, or any description of the actual issue.
