### ISSUE TITLE
A release for ARM Monterey?

### ISSUE THREAD

**Issue by Eugleo** [fxcoudert/gfortran-for-macOS#38]
Hey! Your Fortran fixed my R installation on my Apple Sillicon Mac running Monterey, so big thanks for that! I'd just like to ask if I should keep an eye on this repo and install a newer version of arm-compatible gfortran when you make it available, or if I'm good to go until I hit some explicit error.

**Comment by fxcoudert** [comment]
The Big Sur installer should work well on Monterey. I am working towards an installer for the patched 11.2.0 version for ARM Monterey, probably coming in a couple of days.
