### ISSUE TITLE
Apple M1 with gfortran: library not found for -lm

### ISSUE THREAD

**Issue by magneg** [fxcoudert/gfortran-for-macOS#39]
I have a simple hello.f fortran code giving this output:
gfortran -o hello hello.f 

ld: library not found for -lm
collect2: error: ld returned 1 exit status

I am running macOS 12.0.1 with Xcode 13.2.1. The brew gcc and gfortran is located at /opt/homebrew/Cellar/:

gfortran -v
Using built-in specs.
COLLECT_GCC=gfortran
COLLECT_LTO_WRAPPER=/opt/homebrew/Cellar/gcc/11.2.0_3/bin/../libexec/gcc/aarch64-apple-darwin21/11/lto-wrapper
Target: aarch64-apple-darwin21
…
gcc version 11.2.0 (Homebrew GCC 11.2.0_3)

Seems to me that the library -lm is not found. I appreciate any hints or comments, thanks.

**Comment by fxcoudert** [comment]
This repository is for standalone gfortran packages. Please report your issue with GCC in Homebrew at: https://github.com/Homebrew/homebrew-core/issues/new?assignees=&labels=bug&template=bug.yml

Please include all the information requested, including `brew config` and `brew doctor` output.
