### ISSUE TITLE
Installer for Mac os High sierra

### ISSUE THREAD

**Issue by TejasAvinashShetty** [fxcoudert/gfortran-for-macOS#4]
I can't find any installer for MacOS High Sierra

**Comment by JustForrest** [comment]
I'm also running High Sierra on my Mac. I installed gfortran using the Mojave installer, and I was able to compile some simple programs. However, I was unable to run any compiled code. Anytime I try to run compiled code, my system just hangs. When that didn't work, I tried installing the gfortran build for Sierra over the top of the gfortran Mojave installation. This did not fix the problem. 

Is High Sierra unsupported? Or, did I screw up by not installing the Sierra build first?
