### ISSUE TITLE
was built for newer macOS version (12.0) than being linked (10.13)

### ISSUE THREAD

**Issue by rpang88** [fxcoudert/gfortran-for-macOS#40]
Dear all

I have just installed gfortran for use with R Studio to run nlmixr

The following message seems to appear:
ld: warning: directory not found for option '-L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin18/8.2.0'
ld: warning: dylib (/usr/local/gfortran/lib/libgfortran.dylib) was built for newer macOS version (12.0) than being linked (10.13)
ld: warning: dylib (/usr/local/gfortran/lib/libquadmath.dylib) was built for newer macOS version (12.0) than being linked (10.13)

I am running MacOS 12 and downloaded gfortran 11.2

Is there a solution to this error?

Many Thanks

**Comment by fxcoudert** [comment]
Something in your build system or R Studio is passing wrong options to gfortran. See:

```
ld: warning: directory not found for option '-L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin18/8.2.0'
```

This is the wrong darwin version, (darwin18) and the wrong gfortran version (8.2.0).

**Comment by rpang88** [comment]
Thanks, any thoughts on how I can resolve this. Its a bit odd as I am using the latest MacOS, and downloaded and installed the appropriate gfortran version 11.2. Ive not had any older versions before

**Comment by fxcoudert** [comment]
> any thoughts on how I can resolve this

As stated above: find what options R studio is passing, and why. This option should not be passed to this version of GCC. It's a problem in R studio.
