### ISSUE TITLE
add topics

### ISSUE THREAD

**Issue by Beliavsky** [fxcoudert/gfortran-for-macOS#41]
I suggest that the topics `fortran-compiler`, `gfortran` be added in the About section.

**Comment by fxcoudert** [comment]
Thanks for suggesting! It is done:

<img width="340" alt="Capture d’écran 2022-02-13 à 14 57 16" src="https://user-images.githubusercontent.com/1980544/153756457-3025b627-b769-4342-9e7d-e039f77dc649.png">
