### ISSUE TITLE
Notarized and signed package for gfortran 10.2 for Catalina (macOS 10.15)

### ISSUE THREAD

**Issue by MeganS92** [fxcoudert/gfortran-for-macOS#42]
Hi, 

Similar to issue [#27](https://github.com/fxcoudert/gfortran-for-macOS/issues/27) , I am having this problem still with gfortran 10.2 (ie “gfortran.pkg” can’t be opened because Apple cannot check it for malicious software.) And obviously my work IT admin will not easily overwrite this permission to allow installation given this warning. 

For work purposes, I can't upgrade my work Mac OS easily to BigSUR and am still stuck with Catalina (10.15). Are we able to get a notarized and signed package version for gfortran 10.2 as well so we can install this easily for those using Catalina 10.15? 

Thanks so much. 

Kind regards,
Megan.

**Comment by fxcoudert** [comment]
No, I don't plan on making a notarised installer for Catalina, sorry. You will have to install from another source, e.g. [Homebrew](https://brew.sh)
