### ISSUE TITLE
gfortran for OS 12.0 says it's built for Mac OS 12.1

### ISSUE THREAD

**Issue by interior-night** [fxcoudert/gfortran-for-macOS#43]
I've installed the gfortran-ARM-12.0-Monterrey.pkg on my M1 Mac but when I try the command I get...

`ld: warning: dylib (/usr/local/gfortran/lib/libgfortran.dylib) was built for newer macOS version (12.1) than being linked (12.0)`

**Comment by fxcoudert** [comment]
This is a warning only, and probably not a problem, unless you see other symptoms. What are your compilation flags, and your current macOS version?

**Comment by interior-night** [comment]
The warnings disappeared after updating from 12.0 to 12.2 (as one might expect) so not sure if there were any other symptoms. Should be safe to close the issue!
