### ISSUE TITLE
Cross-compilation from Intel to ARM64

### ISSUE THREAD

**Issue by pchanial** [fxcoudert/gfortran-for-macOS#47]
Hello,
I was wondering if it would be possible to make the Intel dmg packages (MacOS 11 & 12)  handle -march=armv8.5-a or a broader family of architectures to enable cross-compilation.
Since there are not yet github-hosted M1 runners, I'd like to have a go at cross-compiling from a x86_64 runner.

**Comment by andyfaff** [comment]
For the scipy project we use a x86_64 build --> arm64 gfortran cross compiler, installed using https://github.com/scipy/scipy/blob/main/tools/wheels/gfortran_utils.sh, https://github.com/isuruf/gcc/releases/download/gcc-10-arm-20210728/gfortran-darwin-arm64.tar.gz
