### ISSUE TITLE
get error 'library not found for -lSystem' when compiling with gfortran (8.2) on Mac Mojave

### ISSUE THREAD

**Issue by MartinTong** [fxcoudert/gfortran-for-macOS#5]
I just installed gfortran8.2 on my Mac Mojave. Already installed Xcode10.1. I get this 'library not found for -lSystem' error when compiling a simple 4-line code (hellowWorld.f) with gfortran, i.e.
$ gfortran helloWorld.f

Please help.
Thanks

**Comment by EcMscS** [comment]
I had the same problem.  I had to install the Xcode Command Line Tools first then try it again.  Just go to the terminal and type this to install it: xcode-select --install

Then try compiling it again. It got rid of the error for me.

**Comment by MartinTong** [comment]
Thanks for the advice.


Sent from Yahoo Mail for iPhone


On Tuesday, February 4, 2020, 1:40 PM, Jeff Lai <notifications@github.com> wrote:


I had the same problem. I had to install the Xcode Command Line Tools first then try it again. Just go to the terminal and type this to install it: xcode-select --install

Then try compiling it again. It got rid of the error for me.

**Comment by fxcoudert** [comment]
Yes, these installers need the Apple command line tools. `xcode-select --install` will install them for you.
