### ISSUE TITLE
post-install documentation

### ISSUE THREAD

**Issue by DeveloperKev** [fxcoudert/gfortran-for-macOS#50]
Hi,
i was hoping if u could add the necessary steps into readme.
i.e setting up path globally, commands to symlink, etc valuable.

i think, adding path to zshrc is not a clean solution rather than adding globally. thanks.

**Comment by DeveloperKev** [comment]
@fxcoudert any thoughts?

**Comment by fxcoudert** [comment]
I will look at the doc when I build the next package. The package clearly documents where the binaries are installed, so users can chose the solution that is best for them: call with full path, update their `PATH` locally or globally, use an alias, etc.

**Comment by DeveloperKev** [comment]
newer versions of gcc is slower, we all know.
is the speed difference noteworthy in arm mac?
