### ISSUE TITLE
gfortran 12.2 for Intel ETA

### ISSUE THREAD

**Issue by gganis** [fxcoudert/gfortran-for-macOS#52]
Dear Developers,

Thank you very much for providing these fortran builds for MacOsX.
We still have some Ventura@Intel build machines and one of our projects needs to build some fortran packages.
So we were wondering if there is any time estimate for the availability of gfortran-Intel-12.2-Ventura.dmg .
 
Kind regards,
Gerardo Ganis

**Comment by mdu4003** [comment]
Dear Developers, 
Like gganis, I have the same issue. 
When will gfortran be available for Intel?
Best regards, 
Angeles

**Comment by fxcoudert** [comment]
gfortran 14.1 is released for both ARM and Intel: https://github.com/fxcoudert/gfortran-for-macOS/releases/tag/14.1-sonoma
