### ISSUE TITLE
is mieee-fp supported with arm64?

### ISSUE THREAD

**Issue by chengdang** [fxcoudert/gfortran-for-macOS#53]
Hello, I'm trying to compile a fortran model on macOS Ventura (macOS 13, M2 chip), with GCC 12.2 Arm (downloaded here https://github.com/fxcoudert/gfortran-for-macOS/releases, and/or installed with homebrew)

It seem `mieee-fp` is not supported in this environment? Is there a new flag equivalent to `mieee-fp`? Thank you!
```
gfortran: error: unrecognized command-line option '-mieee-fp'
configure:1992: $? = 1
configure:2030: result: no
configure: failed program was:
|       program main
|
|       end
configure:2035: error: in ‘$path’:
configure:2037: error: Fortran compiler cannot create executables
See `config.log' for more details
```

**Comment by fxcoudert** [comment]
This flag should probably not be used. See https://stackoverflow.com/questions/75805477/what-is-the-equivalent-of-gfortran-flag-mieee-fp-on-macos-ventura-m2-gcc-12-2 and https://github.com/iains/gcc-12-branch/issues/20
