### ISSUE TITLE
MacOS Bellhop.exe not appearing 

### ISSUE THREAD

**Issue by DylanSaraiva** [fxcoudert/gfortran-for-macOS#57]
First off, I want to preface this by saying I am a complete novice and I'm unsure where I am going wrong throughout this process. However, in following the installation guide 
https://patel999jay.github.io/post/bellhop-acoustic-toolbox/MacOS_Installation_Manual.pdf
I believe I am following the steps correctly however once I try to open up the Jupyter notebook aspect I do not have any file called Bellhop.ipynb. 

I am unsure if I am possibly not installing the package correctly but I used the package for MacOS 12.1 for Monterey with an Intel. Although the difference from my experience and the installation guide is my path is significantly longer than that which is shown and maybe that could be my misstep. Any information would be greatly appreciated!

**Comment by fxcoudert** [comment]
I have no idea what Bellhop is, but I think you should report the issue to them, as it seems marginally related to gfortran (at best).
