### ISSUE TITLE
missing libSystem.B.dylib during execution

### ISSUE THREAD

**Issue by gakabani** [fxcoudert/gfortran-for-macOS#58]
I am no expert, so I apologize if this may be an issue that has been addressed before.
I have a Mac Silicon M2 OS Ventura 13.5.2 (22G91).
I installed XOCODE, command line utilities, and gfortran (https://github.com/fxcoudert/gfortran-for-macOS)

GNU Fortran (GCC) 12.2.0

My code runs perfectly on my Mac Intel processor; however, on the Mac Silicon, the execution gives me the error described below, indicating that libSystem.B.dylib is missing.

dyld[67029]: dyld cache '(null)' not loaded: syscall to map cache into shared region failed
dyld[67029]: Library not loaded: /usr/lib/libSystem.B.dylib
  Referenced from: <28252600-BB7B-336B-AB15-3687F43881F0> /Users/gamalakabani/Applications/TALYS_CODE/talys/bin/talys
  Reason: tried: '/usr/lib/libSystem.B.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/lib/libSystem.B.dylib' (no such file), '/usr/lib/libSystem.B.dylib' (no such file, no dyld cache), '/usr/local/lib/libSystem.B.dylib' (no such file)
./verify: line 12: 67029 Abort trap: 6           $talys < talys.inp > talys.out

I would appreciate any help you can give me.

Thank you

**Comment by fxcoudert** [comment]
Probably too late to help. I have no idea why dyld wouldn't find its own system library.
