### ISSUE TITLE
Mac OS ARM64 is not currently supported in the sources in gcc.gnu.org version.

### ISSUE THREAD

**Issue by gakabani** [fxcoudert/gfortran-for-macOS#59]
I encountered an execution problem with a legacy code using a Mac M2 machine running Ventura.
I contacted the GCC GNU team and was told that the current version of GCC still needs to support GCC aarch64-darwin.

"GCC upstream does not have support for aarch64-darwin yet.
So you will need to report this first to homebrew."

Homebrew and this site indicate that Apple Silicon machines are supported by GNU GCC, which needs to be corrected. 
Please address this confusing issue.
Where and who gave proof that GNU GCC supports aarch64-darwin?

Thank you

**Comment by fxcoudert** [comment]
The binaries published here (and in Homebrew) are based on a branch maintained by the GCC darwin maintainer, and published at https://github.com/iains/gcc-darwin-arm64
