### ISSUE TITLE
Apple version of xcode (Sonoma) does not match available versions of gfortran

### ISSUE THREAD

**Issue by jkoval02** [fxcoudert/gfortran-for-macOS#61]
For my machine I require gfortran ... Ventura ...  The version of xcode from apple says it is for Sonoma, and does not behave as indicated in your html file, ie for the command xcode-select --install 
the response is "xcode-select not found"

**Comment by fxcoudert** [comment]
`/usr/bin/xcode-select --install` should always be available on any recent macOS.
