### ISSUE TITLE
Problem with gfortran (on mac M1 but not on Mac intel)

### ISSUE THREAD

**Issue by tof92130** [fxcoudert/gfortran-for-macOS#62]
Hello

I am using the libmeshb developed by Loic Marechal in order to read mesh files generated with INRIA programs. 

We are facing something that seems to be a bug on mac M1. I don't know exactly where to report the bug so I open an issue here. 

To reproduce de bug simply download the libmeshb from GitHub: 

git clone https://github.com/LoicMarechal/libMeshb.git

To compile de program enter:

mkdir build
cd build
cmake --install-prefix=/tmp/ ..
make
make install

Then:

cd /tmp/share/libMeshb/examples/
./test_libmeshb_f77

On mac Intel it works and on Mac M1 it crashes. 

PS: the same bug also occurs on Raspberry pi4 with gfortran.

**Comment by LoicMarechal** [comment]
Hi.
The bug occurs when calling a C variable arguments procedure from Fortran.
This feature is deprecated and raises warnings since GCC/Gfortran 9+ (even with -std=legacy).
But it is working anyway on all Intel/AMD hardware.
It is crashing only on ARM architecture either running Linux or macOS.

**Comment by fxcoudert** [comment]
Yes, calling C variadic functions from Fortran was never supported. It works “by chance” on some ABIs, but not on Apple Silicon.

It is not possible to call a variadic function from Fortran in a standard conforming (i.e. portable) way.
