### ISSUE TITLE
Intel pretty please

### ISSUE THREAD

**Issue by karlglazebrook** [fxcoudert/gfortran-for-macOS#63]
There is no intel binary release for MacOS gfortran anywhere for Ventura or later. Not here, nor on hpc.sourceforge.net

Here it says 'coming soon' for close to a year. Pretty please can we have this? Ideally for v12 and v13

thanks

**Comment by fxcoudert** [comment]
gfortran 14.1 is released for both ARM and Intel: https://github.com/fxcoudert/gfortran-for-macOS/releases/tag/14.1-sonoma
