### ISSUE TITLE
Installation of petitRADTRANS on Mac 

### ISSUE THREAD

**Issue by Margarida-Graca** [fxcoudert/gfortran-for-macOS#64]
I have a MacBook Pro M2 macOS Sonoma 14.4.1 and I'm having trouble installing petitRADTRANS. I first tried to install gfortran through homebrew and then typed "pip install petitRADTRANS". It returned:

'''
note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for petitradtrans
  Running setup.py clean for petitradtrans
Failed to build petitradtrans
ERROR: Could not build wheels for petitradtrans, which is required to install pyproject.toml-based projects
fatal: destination path 'petitRADTRANS' already exists and is not an empty directory.
'''

Then I installed gfortran through Xcode, as it's said for my type of Mac. I tried to install petitRADTRANS again and the same error came back. Then I used a virtual environment and the installation worked out:

'''
Successfully installed corner-2.2.2 exo_k-1.2.2 h5py-3.11.0 molmass-2023.8.30 nestle-0.2.0 numpy-1.25.2 petitRADTRANS-2.7.6 pymultinest-2.12 seaborn-0.13.2
'''

Then I tried to run the petitRADTRANS code on Jupyter, using python 3.8 and the virtual environment where I installed petitRADTRANS, but it returned the same error:

I runned:

'''
#!git clone https://github.com/JohannesBuchner/MultiNest.git
#%cd /content/MultiNest/build
#!pwd
#!cmake .. 
#!make
#!cp /content/MultiNest/lib/* /usr/lib/
#%cd /content/
#!pip install pymultinest
#!wget -O input_data_red.tar.gz "https://polybox.ethz.ch/index.php/s/V3uTstd8pya6swr/download"
#!tar -xzf input_data_red.tar.gz --warning=no-unknown-keyword
!pip install petitradtrans
!git clone https://gitlab.com/mauricemolli/petitRADTRANS.git
'''

and it returned:

'''
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for petitradtrans
  Running setup.py clean for petitradtrans
Failed to build petitradtrans
ERROR: Could not build wheels for petitradtrans, which is required to install pyproject.toml-based projects
fatal: destination path 'petitRADTRANS' already exists and is not an empty directory.
'''

mentioning warnings about gfortran:

''' gfortran: warning: this compiler does not support x86 (‘-arch’ option ignored)
      ld: warning: ignoring file build/temp.macosx-10.9-x86_64-cpython-39/build/src.macosx-10.9-x86_64-3.9/build/src.macosx-10.9-x86_64-3.9/petitRADTRANS/fortranobject.o, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
      ld: warning: ignoring file build/temp.macosx-10.9-x86_64-cpython-39/build/src.macosx-10.9-x86_64-3.9/petitRADTRANS/fort_specmodule.o, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
'''

How can I solve this?

**Comment by fxcoudert** [comment]
> I have a MacBook Pro M2 macOS Sonoma 14.4.1

But you are trying to install this "petitRADTRANS" for Intel:

```
gfortran: warning: this compiler does not support x86 (‘-arch’ option ignored)
ld: warning: ignoring file build/temp.macosx-10.9-x86_64-cpython-39/build/src.macosx-10.9-x86_64-3.9/build/src.macosx-10.9-x86_64-3.9/petitRADTRANS/fortranobject.o, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
ld: warning: ignoring file build/temp.macosx-10.9-x86_64-cpython-39/build/src.macosx-10.9-x86_64-3.9/petitRADTRANS/fort_specmodule.o, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
```

You have to ask the "petitRADTRANS" developers why that build process is targeting Intel.
