### ISSUE TITLE
gfortran compiler error

### ISSUE THREAD

**Issue by MarcMansfield** [fxcoudert/gfortran-for-macOS#66]
I installed gfortran on my Mac (Sonoma 14.5) using the gfortran-ARM-14.1-Sonoma.dmg link.  When I compile, I get this error:
gfortran: fatal error: cannot execute ‘f951’: execvp: No such file or directory
compilation terminated.
The same error occurs when I try to download from homebrew

**Comment by fxcoudert** [comment]
- In my installer that file should be at `/usr/local/gfortran/libexec/gcc/aarch64-apple-darwin23/14/f951`
- In Homebrew that file should be at `/opt/homebrew/opt/gcc/libexec/gcc/aarch64-apple-darwin23/14/f951`

Hard to guess why it's not there.
