### ISSUE TITLE
uninstall in a clean way

### ISSUE THREAD

**Issue by zhyiyu** [fxcoudert/gfortran-for-macOS#7]
I found out that I need to uninstall `gfortran` and therefore wonder if there is a clean way to do so.

Thanks!

**Comment by fxcoudert** [comment]
Installing by running: `rm -rf /usr/local/gfortran /usr/local/bin/gfortran`
(If running under non root, will require `sudo` before)

**Comment by zhyiyu** [comment]
Thank you! I think I have succeeded!
