### ISSUE TITLE
Install to /opt/local and Versioned install

### ISSUE THREAD

**Issue by imikejackson** [fxcoudert/gfortran-for-macOS#8]
With macOS Catalina access to /usr/local is suspect and not usable when a clean install is performed. Is it possible to generate newer binaries that are rooted in /opt/local AND also versioned such as /opt/local/gfortran-8.2 so that we can have multiple versions of gfortran on our systems?

Thanks

**Comment by rsparapa** [comment]
Yes, this a problem for me too as I just discovered yesterday.  However, I don't think we need new binaries, although, that would help.  Inspired by Mike Jackson's issue, I think you can just move /usr/local/gfortran to /opt/local/gfortran.  Will test when I get a chance.

**Comment by fxcoudert** [comment]
What do you mean by:

> With macOS Catalina access to /usr/local is suspect

This local is designed for installation of system-wide local software, and is used not only by this package, but by other distributions, such as [Homebrew](https://brew.sh).

**Comment by rsparapa** [comment]
Yes, I know that.  However, I had developed an issue with Catalina while linking a compiled library as I was trying to install an R package.  I was unable to track this down via a Google search (if that means anything ;o)  The closest thing that I could come up was this Issue.  By adding Terminal to the Developer Tools setting in Privacy, this issue went away so I assumed it was legitimate. However, right now, I can't replicate it so I'm suspicious.  The error message from clang++: "/usr/local/lib/libgfortran.3.dylib: code signature in (/usr/local/lib/libgfortran.3.dylib) not valid for use in process using Library Validation: library load disallowed by system policy".  Have you ever seen anything like this before?  Thanks

**Comment by rsparapa** [comment]
Aha!  So this comes from what Apple calls a "quarantine" for files that it can't ascertain the veracity of.  You can vouch for these file as follows
```
cosmos:bnptools rsparapa$ ls -l@ /usr/local/lib/libgfortran.3.dylib
-rwxr-xr-x@ 1 rsparapa  staff  1484568 Apr 30  2017 /usr/local/lib/libgfortran.3.dylib
	com.apple.quarantine	     57 
cosmos:bnptools rsparapa$ sudo xattr -d com.apple.quarantine /usr/local/lib/libgfortran.3.dylib
cosmos:bnptools rsparapa$ ls -l@ /usr/local/lib/libgfortran.3.dylib
-rwxr-xr-x  1 rsparapa  staff  1484568 Apr 30  2017 /usr/local/lib/libgfortran.3.dylib
```
